kind: Service
apiVersion: v1
metadata:
  name: django-backend-poll-app-jenkins-dashboard-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    pod: django-backend-poll-app-jenkins-dashboard-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalance
